### ISSUE TITLE
White icon problem

### ISSUE THREAD

**Issue by happysurf** [ettoolong/MaximizeVideo#1]
The option  > White icon, in reality set a gray color very difficult to see with the default dark theme and in dark Personas.
With a dark Personas all Firefox icons are inverted in white.

![gray icon](https://user-images.githubusercontent.com/13637587/36075745-7ee96c70-0f53-11e8-8f7f-4ab540a56bc2.png)

The personas used is this: https://addons.mozilla.org/en-US/firefox/addon/aparker-s-space-theme/
Firefox 59beta on W10.

**Comment by ettoolong** [comment]
This snapshot looks similar the button is in the "disabled" state.

I install the same theme:

disabled: ( for example: you switch to about:addons tab )
![disable](https://user-images.githubusercontent.com/909570/36954763-1fbdbcca-205f-11e8-991f-de6ca48caeb5.png)

enabled:
![enable](https://user-images.githubusercontent.com/909570/36954764-211be6c8-205f-11e8-8819-2615e8840ab9.png)

I hope this answers your question.

**Comment by happysurf** [comment]
You are right, in active mode the icon is more bright, not the same color of Firefox toolbar icons but is OK.
