### ISSUE TITLE
hlstester.com] ratio problem

### ISSUE THREAD

**Issue by wadawada** [ettoolong/MaximizeVideo#11]
Hi. The ratio of the video does not remain the same when maximized on this website. Can you solve the problem? Thanks

Chrome on Windows 10

https://www.hlstester.com/
with input
https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4

**Comment by ettoolong** [comment]
@wadawada Is this question related to #9? Can you test it again on version 0.0.10?

Thanks for your feedback.

**Comment by wadawada** [comment]
I retested it and it works now
thanks
