### ISSUE TITLE
gimy.tv] problems with progress bar

### ISSUE THREAD

**Issue by wadawada** [ettoolong/MaximizeVideo#12]
https://gimy.tv/vod-play-id-84898-src-12-num-1.html
The video can be maximized with proper ratio in Chrome on Windows 10, but the progress bar/controls is not showing. Play/Pause, changing progress is not possible when maximized
Can you solve the problems? Thanks

**Comment by ettoolong** [comment]
@wadawada This is so weird and I spend a lot of time to find out the problem.
I fixed this bug in Maximize Video 0.0.10, you can test it again.

Thank for your feedback.

**Comment by wadawada** [comment]
It is indeed very weird
I retested it and it works now
thanks
