### ISSUE TITLE
appledaily.com problem

### ISSUE THREAD

**Issue by wadawada** [ettoolong/MaximizeVideo#19]
can't detect videos on 
https://tw.appledaily.com/new/realtime/20190617/1585133
https://hk.sports.appledaily.com/sports/realtime/article/20190616/59721103

please fix it thanks

**Comment by ettoolong** [comment]
@wadawada  These sites need login. After testing, there is no problem.
<img width="936" alt="snapshot" src="https://user-images.githubusercontent.com/909570/59669078-21fc4100-91ec-11e9-8763-04fc6671f16a.png">

**Comment by ettoolong** [comment]
@wadawada These sites need login. After testing, there is no problem.

<img width="936" alt="screenshot" src="https://user-images.githubusercontent.com/909570/59676212-a0131480-91f9-11e9-8ee4-4fffd24e8d12.png">

**Comment by wadawada** [comment]
I tried to reinstall but still somehow it doesn't work on this website for me
I don't understand why?
Basically I can't see the red box on this website, but I believe the extension has no exclude function?

**Comment by wadawada** [comment]
I tried to reinstall but still somehow it doesn't work on this website for me
Basically I can't see the red box on this website on Chrome
but later I install Firefox, it does work on Firefox, so I believe it's a bug on Chrome/ Chrome bug
