### ISSUE TITLE
[Suggestion] Hide mouse cursor

### ISSUE THREAD

**Issue by happysurf** [ettoolong/MaximizeVideo#2]
Is possible hide also the mouse cursor when the video status bar automatically disappear?
Thanks.

**Comment by ettoolong** [comment]
Maybe we can add a new option, something like:

1. Hide mouse cursor after N seconds.
2. When you move mouse, the cursor will show again.

**Comment by ettoolong** [comment]
Update version 0.0.5:
1. Add options for auto hide mouse cursor.

**Comment by happysurf** [comment]
Thank you very much for your work, your extension is fantastic.
