### ISSUE TITLE
Dark icon

### ISSUE THREAD

**Issue by happysurf** [ettoolong/MaximizeVideo#21]
In the Firefox addons dark page, the MaximizeVideo icon is hard to see, will be great make a medium gray or something like that.

![Dark Icon](https://user-images.githubusercontent.com/13637587/66698321-65b81080-ecdd-11e9-9063-aa7e6aad127a.png)

For apply the dark theme set **browser.in-content.dark-mode** to **true** **(default in Firefox 70 beta).**

**Comment by ettoolong** [comment]
<img width="687" alt="截圖 2019-12-13 23 57 34" src="https://user-images.githubusercontent.com/909570/70813542-99f69d00-1e04-11ea-826c-49b43c875edd.png">
Update v0.0.13
