### ISSUE TITLE
Unable to maximize videos using Kaltura player (e.g. O’Reilly Online Learning)

### ISSUE THREAD

**Issue by adduc** [ettoolong/MaximizeVideo#24]
Hi,

I'm having trouble using the Firefox extension to maximize videos within O'Reilly's [Online Learning](https://www.oreilly.com/) site (behind a paywall). The site appears to be using the Kaltura Player.

To Replicate:
* Visit http://player.kaltura.com/docs/
* Play the video at the top of the page.
* Attempt to maximize the video.
* Observe that no videos were found to maximize.

![Screenshot from 2019-12-15 17-27-36](https://user-images.githubusercontent.com/44527/70872982-3d0ff980-1f60-11ea-9e75-20fd8aeccf07.png)

**Comment by ettoolong** [comment]
Update v0.0.14

For some technical issue, this fix only for Firefox.

Thank for your feedback.

**Comment by adduc** [comment]
Thanks, I can confirm this works now in Firefox.
