### ISSUE TITLE
It breaks Ctrl + number to switch to tab

### ISSUE THREAD

**Issue by pintassilgo** [ettoolong/MaximizeVideo#30]
In both Firefox an Chrome, we can switch to tab by pressing Ctrl + number, like Ctrl + 1 to go to the first tab. But this hotkey doesn't work if there is a maximized video in current tab. Note: I'm talking about number keys above the letters, not numpad keys. 

Instead, video progress skips to number * 10%, this is VERY unwanted and may lead us to lose progress in long videos.

**Comment by ettoolong** [comment]
Fixed and update v0.0.14(Firefox), v0.0.13(Chrome), Thank for your feedback. 😀
