### ISSUE TITLE
Doesn't work anymore on the new Firefox 79.0

### ISSUE THREAD

**Issue by matt00112233** [ettoolong/MaximizeVideo#33]
After updating to Firefox 79.0, the add-on doesn't work anymore when I click on the icon, the video becomes red but never get maximized 

![Annotation 2020-08-01 075437](https://user-images.githubusercontent.com/36396935/89101273-66d14000-d3cc-11ea-917f-09c57c1d77a2.jpg)
![Annotation 2020-08-01 075437](https://user-images.githubusercontent.com/36396935/89101288-85373b80-d3cc-11ea-9872-ab59a09b6dae.jpg)

**Comment by ettoolong** [comment]
Hi @matt00112233 ,

I can't reproduce this problem, (test on macOS, Firefox 79.0 and 80.0b2)
1. Can you please check the preference, make sure the option **Auto maximize first video element** is checked.
2. Can you  try to click on the highlight area to see if the video will get maximized?

**Comment by vest816** [comment]
Hello @matt00112233 and @ettoolong 

I'm on Firefox 79.0, Windows 10. I think I've pinpointed the issue. I was experiencing the same problem earlier and did some poking around in the app's options menu. It seems the "Keep original controls on YouTube" option was causing it. Try unchecking that, and see if the issue persists.

**Comment by ettoolong** [comment]
Hi @vest816, @matt00112233,
The last update I remove the **tabs** permission cause this issue, seems I need add it back in next update,

Thanks for your feedback.

**Comment by ettoolong** [comment]
Update v0.0.16 for Firefox

**Comment by vest816** [comment]
Just checked and tested around with the different options toggled on and off. Works on Twitch. Works on YouTube. And works on the few other streaming sites I tested it out with. Seems fixed for me! Thanks @ettoolong

**Comment by matt00112233** [comment]
Thanks a lot, I'll try later and report back
