### ISSUE TITLE
拓展名称是不是有点太长了？

### ISSUE THREAD

**Issue by runningcheese** [ettoolong/MaximizeVideo#4]
![screenshot](https://user-images.githubusercontent.com/4476264/38883423-6f1fb784-429f-11e8-892e-e451868c232a.jpg)

拓展非常棒，很喜欢，希望能能变得更好更完美！
拓展名称有点长，可否变得短一些？还有拓展 Popup window 也一样，有点太长了~

**Comment by ettoolong** [comment]
![38883423-6f1fb784-429f-11e8-892e-e451868c232a](https://user-images.githubusercontent.com/909570/38907721-b24cfd64-42ef-11e8-8712-1b1f91a28e2e.jpg)
I don't know why you get this problem. The text (with red underline) is description of the add-on instead of the name.

**Comment by ettoolong** [comment]
Where did you download the add-on? Seems your icon and localization text are different from original. Please make sure you download them from official source. Thanks.
