### ISSUE TITLE
请教这段代码的问题

### ISSUE THREAD

**Issue by Jerry-1984** [ettoolong/MaximizeVideo#6]
在一个UC脚本中有以下代码，控制视频窗口最大化以及弹出的，现在貌似失效了，是因为本扩展改了语法吗？请问现在该怎么写呢？
`{
				label : '弹出视频',
				image :"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAcUlEQVQ4jbXTvQmFQBBF4S+wCMNXgh1oRfZmblsiYqCBBr7FnxHZCxMt9+yZhSVDfliC8yn5AQV6DBgxJaU/wNN+NeZ9LgFnBsdyvVuEAWnZW4O0DF0UUNoerr0wCxlUd4UI4PZGNF8B8cMoIPvnOc0KNDA9zZlUdtUAAAAASUVORK5CYII=",
				oncommand: 'document.getElementById("maximizevideo_ettoolong-browser-action").click();document.getElementById("popupwindow_ettoolong-browser-action").click();',
},
 {
				label : '宽屏模式',
				image :"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAUUlEQVQ4jWNgoAL4jwMTrQ6bYlIshxvgycDA8AyPTTD8DKoWw4BnDAwM1kTYag1Vi2EAKV7BqoccAwgLDg0DKA5EqkUjxQmJHAA3gKLMRBEAAPmLTP1ErtdyAAAAAElFTkSuQmCC",
				oncommand: 'document.getElementById("maximizevideo_ettoolong-browser-action").click();',
},{
				label : '小窗模式',
				image :"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAQ0lEQVQ4jWNgoBL4TyZGMYAcS2ljALGG4XUBMQYS9MJ/PHJEGQATJ8sAnNFFqguIBsQYQHFCwhdTg8QAQpkGbxiQDQDkmEO9y3ip2QAAAABJRU5ErkJggg==",
				oncommand: 'document.getElementById("popupwindow_ettoolong-browser-action").click();',
},`

**Comment by ettoolong** [comment]
Sorry, I don't know how it work.
If you need control functions by script, see below document:
[Maximize video by other add-on](https://github.com/ettoolong/MaximizeVideo/wiki/Maximize-video-by-other-addon)
[Open pop-up window by other add-on](https://github.com/ettoolong/PopupWindow/wiki/Open-popup-window-by-other-addon)

Thanks.
