### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by davisstu** [ettoolong/MaximizeVideo#64]
Chrome has indicated that this extension will no longer be supported once it transitions to Manifest v3. Is there a roadmap in place to update the extension to ensure compatibility with Manifest v3?

**Comment by hyperion4** [comment]
> Chrome has indicated that this extension will no longer be supported once it transitions to Manifest v3. Is there a roadmap in place to update the extension to ensure compatibility with Manifest v3?

I hope it gets updated. But I have the feeling this extension is basically abandoned. The last update was 3 years ago.
If it doesn't get updated you can use the Maximize Video userscript instead.
Tampermonkey has been updated to MV3 and the Maximize Video script works fine in most sites I have it tested.
https://greasyfork.org/en/scripts/4870-maximize-video

**Comment by davisstu** [comment]
> > Chrome has indicated that this extension will no longer be supported once it transitions to Manifest v3. Is there a roadmap in place to update the extension to ensure compatibility with Manifest v3?
> 
> I hope it gets updated. But I have the feeling this extension is basically abandoned. The last update was 3 years ago. If it doesn't get updated you can use the Maximize Video userscript instead. Tampermonkey has been updated to MV3 and this Maximize Video script works fine in most sites I have it tested. https://greasyfork.org/en/scripts/4870-maximize-video

I fear you might be right. Thanks for the userscript equivalent, though - very handy.

**Comment by ettoolong** [comment]
Since I've been so busy with my job, I haven't updated this extension in three years. I thought it was still working for the past year. I have updated it to Manifest v3 and I'm waiting for Google review. You can check out the source code in chrome-mv3 branch.

I'm still trying to solve the issue that video element inside the iframe, hoping I'll fix it in the next update.

**Comment by davisstu** [comment]
@ettoolong It looks like the update has reached the Chrome store. Unfortunately, all functionality has gone. Neither the manual or automatic option work like they did under the previous versions. It just seems to overlay the page, and doesn't focus the video etc like the previous version. Any ideas?

**Comment by ettoolong** [comment]
@davisstu I just tested it on youtube and twitch and it works fine.
Can you disable and re-enable the extension and try again?

**Comment by davisstu** [comment]
@ettoolong Enabled and re-enabled and still the same issue. Doesn't work on YT or Twitch (your use cases either). I was literally using the previous version this morning which worked, then it updated and now it doesn't. I'm on latest stable chrome on MacOS latest, btw.

Testing it in Incognito it works on YouTube but doesn't work on other HTML5 video it previously worked on.

**Comment by ettoolong** [comment]
@davisstu Can you provide a website URL for me to test?

**Comment by davisstu** [comment]
@ettoolong A grey area legally but as a test case this is a site I use. All the streams on this site worked with previous version, now none of them do. https://strikeout.im/

**Comment by ettoolong** [comment]
Chrome shows `ERR_CONNECTION_REFUSED` when I visit this site. 🙁

**Comment by ettoolong** [comment]
> @ettoolong Ok try this legit one - same issue https://www.bbc.co.uk/reel/video/p0jgsff2/the-scientists-drilling-into-an-active-icelandic-volcano

@davisstu In this case, it will be fixed in version 0.0.23 (waiting for google review), but I have no idea if other sites can be fixed. Obviously, this is a different problem than site `strikeout.im`.

<img width="1267" alt="截圖 2024-08-20 00 25 17" src="https://github.com/user-attachments/assets/0e18e2d2-3e7c-4a4d-b6a2-1b4202a1a527">

**Comment by davisstu** [comment]
@ettoolong 0.0.23 has fixed the issues noted above 👍

**Comment by hyperion4** [comment]
I've tested the latest MV3 version in every site I was using the MV2 version and it works great in all of them.
Thank you @ettoolong for the great update.
