### ISSUE TITLE
Ratio lossed on Euronews.com

### ISSUE THREAD

**Issue by StanGets** [ettoolong/MaximizeVideo#9]
Hi,

_Maximize Video_ 0.0.9 / _Firefox_ 63.0 (x64) / _Windows_ 7 (x64)

Maximized video doesn't keep the ratio at https://www.euronews.com/live
This is at this time the only issue I've encountered and I'm aware it's euronews.com the culprit. Nevertheless if _MaximizeVideo_ can deal with the odd video display of Euronews it'd be great.

Thanks!

**Comment by ettoolong** [comment]
@StanGets Sorry for the late reply, I fixed this bug in Maximize Video 0.0.10, you can test it now.
Thank for your feedback.

**Comment by StanGets** [comment]
**Maximize Video 0.0.10** / Firefox 65.0.2 (x64) / Windows 7 (x64) :

_Maximized Video_ now keeps the ratio at https://www.euronews.com/live

@ettoolong : thanks!
